services:
  app:
    # Changed from build to image
    image: ${DOCKERHUB_USERNAME}/express-app:latest
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db

  db:
    # Changed from build to image
    image: ${DOCKERHUB_USERNAME}/my-app-db:latest
    command: mongod --port 6969
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


