name: CI-Pipeline
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo code
      uses: actions/checkout@v4

    - name: Construct Environment Configuration file
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "MONGO_PORT=${{ secrets.MONGO_PORT }}" >> .env
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
        echo "NODE_ENV=test" >> .env
        echo "MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_INITDB_ROOT_USERNAME}}" >> .env
        echo "MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_INITDB_ROOT_PASSWORD}}" >> .env

    - name: Start Stack via Docker Compose
      run:  docker compose up -d --build
    
    - name: Execute Live App Sanity Check
      run: |
        echo "Waiting for app and database stack to stabilize..."
        sleep 10
        docker compose ps
        
        echo "Testing connection to live endpoint..."
        curl --silent --fail http://localhost:${{ secrets.PORT }}/ || (echo "❌ Health check failed! Printing application crash logs:" && docker compose logs app && exit 1)

    - name: Teardown Testing Workspace
      if: always()
      run: docker compose down -v